### PR TITLE
Add service definition for PsrAclCache

### PR DESCRIPTION
**Pull request by mbabker**
Requires https://github.com/symfony/security-acl/pull/72

This adds the service definition for the new `Symfony\Component\Security\Acl\Domain\PsrAclCache` class added to the component for use as a cache service.

### CODE REVIEW

**Review by derrabus — CHANGES_REQUESTED** [review]
Adding the service definition alone won't be enough. The bundle would currently still alias the Doctrine cache as `security.acl.cache`, so the new cache service won't be used.

**Comment by mbabker** [comment]
> The bundle would currently still alias the Doctrine cache as `security.acl.cache`, so the new cache service won't be used.

That alias is set from the `cache.id` config node (which defaults to null), it doesn't automatically map to the Doctrine cache implementation.

**Comment by derrabus** [comment]
Right, but the bundle does not integrate that new cache either.

How about a new option `pool` where I can specify one of the cache pools configured by FrameworkBundle that I want to be wired as ACL cache? Of course, we should throw an exception if the app specifies both options, `id` and `pool`.

**Comment by mbabker** [comment]
I've tweaked the bundle config to add the new option and adjusted everything else accordingly.  Also added tests covering the cache service setup since none existed previously.

**Review by wouterj — APPROVED** [review]

**Comment by wouterj** [comment]
Thank you @mbabker!

**Pull request merged**
