### PR TITLE
SF7 compatibility changes

### PR DESCRIPTION
**Pull request by hgabka**
Symfony 7 compatibility changes.
symfony/security-acl package still have some incompatibility issues, so a fix is also needed in that package

### CODE REVIEW

**Comment by xabbuh** [comment]
Can you please update the CI config (`.github/workflows/ci.yml`) to also run a job with Symfony 7 installed?

**Comment by hgabka** [comment]
Added the test on PHP 8.2 and syfony 7

**Comment by acrobat** [comment]
Is there anymore work needed here or can I help move this PR forward?

**Comment by xabbuh** [comment]
The failing tests seem to be related to these changes.

**Comment by acrobat** [comment]
@xabbuh I've finished this PR and fixed the failing tests in #45!

**Comment by xabbuh** [comment]
closing in favour of #45

**Pull request closed without merging**
