### PR TITLE
Allow Symfony 7 and fix incompatibilities

### PR DESCRIPTION
**Pull request by acrobat**
Finished PR #44

### CODE REVIEW

**Review by xabbuh — APPROVED** [review]

**Comment by colesnic89** [comment]
@xabbuh  Is there any progress here?

**Comment by chq81** [comment]
Hey! It would be great if this could be merged :)

**Comment by xabbuh** [comment]
Thank you @acrobat.

**Comment by chq81** [comment]
Thanks a lot, @xabbuh. Could the main branch be tagged so the symfony 7 update is usable?

**Comment by xabbuh** [comment]
done, I have tagged 2.4.0 with these changes

**Comment by chq81** [comment]
@xabbuh Thank you very much!

**Pull request merged**
